// packages/tenon-preset-materials/src/web/Atom/Text/Text.vue
<template>
  <span
    v-bind="$attrs"
    class="tenon-material-text"
    :style="props.style || props.__tenon_material_instance__.propMeta.style.default"
    ref="root"
    >{{ props.text || `Vue: ${props.__tenon_material_instance__.propMeta.text.default}` }}</span
  >
</template>

<script setup lang="ts">
import { shallowRef } from "vue";
import {
  createTenonEvent, useComponentLifeCycle,
  registerCommonHooks, TenonComponentLifeCycle,
} from "@tenon/material-foundation";
import { TextProps } from "./interface";
import { RendererHost } from "@tenon/engine";

const props = defineProps<TextProps>();

const root = shallowRef<HTMLElement | null>(null);
const eventMeta = props.__tenon_event_meta__;

registerCommonHooks(RendererHost.Vue, eventMeta, root, props.bridge);
const clickHandler = (e) => {
  console.log(props.__tenon_material_instance__.name, createTenonEvent("onClick"), e);
};
const doubleClickHandler = (e) => {
  console.log(
    props.__tenon_material_instance__.name,
    createTenonEvent("onDoubleClick"),
    e
  );
};
props.bridge.register(createTenonEvent("onClick"), clickHandler);
props.bridge.register(createTenonEvent("onDoubleClick"), doubleClickHandler);

useComponentLifeCycle(RendererHost.Vue, TenonComponentLifeCycle.UnMount, () => {
  props.bridge.unRegister(createTenonEvent("onClick"), clickHandler);
  props.bridge.unRegister(createTenonEvent("onDoubleClick"), doubleClickHandler);
});
</script>

<style lang="scss" scoped>
@import url("./Text.scss");
</style>
../../../../../tenon-materials/src/events

// packages/tenon-materials/src/components/web/Atom/Text/Text.react.tsx
import React, { FC, useEffect, useRef } from 'react';
import { TextProps } from './interface';
import { createTenonEvent, useEventMeta } from '../../..';
import { RendererHost } from '@tenon/engine';

export const TextReact: FC<TextProps<React.CSSProperties>> = (props) => {
  const {
    style,
    text,
    bridge,
    __tenon_event_meta__,
    __tenon_material_instance__,
  } = props;
  const root = useRef<HTMLSpanElement>(null);
  useEventMeta(RendererHost.React, __tenon_event_meta__, root, bridge);
  useEffect(() => {
    bridge.register(createTenonEvent("onClick"), (e) => {
      console.log(__tenon_material_instance__.name, createTenonEvent("onClick"), e);
    });
    bridge.register(createTenonEvent("onDoubleClick"), (e) => {
      console.log(
        __tenon_material_instance__.name,
        createTenonEvent("onDoubleClick"),
        e
      );
    });
  }, []);
  return (
    <>
      <span ref={root} style={style}>{text}</span>
    </>
  ) as ReturnType<FC<TextProps<React.CSSProperties>>>;
}
