// packages/tenon-preset-materials/src/web/Atom/Text/Text.react.tsx
import React, { FC, useCallback, useRef } from 'react';
import { shallowRef } from 'vue';
import { TextProps } from './interface';
import {
  TenonComponentLifeCycle,
  createTenonEvent,
  useComponentLifeCycle,
  registerCommonHooks
} from '@tenon/material-foundation';
import { RendererHost } from '@tenon/engine';
import "./Text.scss";

export const TextReact: FC<TextProps<React.CSSProperties>> = (props) => {
  const {
    style,
    text,
    bridge,
    __tenon_event_meta__,
    __tenon_material_instance__,
  } = props;
  const root = useRef<HTMLSpanElement>(null);
  const reactiveRootRef = shallowRef<HTMLSpanElement | null>(null);
  const clickHandler = useCallback((e) => {
    console.log(__tenon_material_instance__.name, createTenonEvent("onClick"), e);
  }, []);
  const doubleClickHandler = useCallback((e) => {
    console.log(
      __tenon_material_instance__.name,
      createTenonEvent("onDoubleClick"),
      e
    );
  }, []);

  useComponentLifeCycle(RendererHost.React, TenonComponentLifeCycle.Mount, () => {
    reactiveRootRef.value = root.current;
    bridge.register(createTenonEvent("onClick"), clickHandler);
    bridge.register(createTenonEvent("onDoubleClick"), doubleClickHandler);
  });

  registerCommonHooks(RendererHost.React, __tenon_event_meta__, reactiveRootRef, bridge);

  useComponentLifeCycle(RendererHost.React, TenonComponentLifeCycle.UnMount, () => {
    reactiveRootRef.value = null;
    bridge.unRegister(createTenonEvent("onClick"), clickHandler);
    bridge.unRegister(createTenonEvent("onDoubleClick"), doubleClickHandler);
  });
  return (
    <>
      <span className="tenon-material-text" ref={root} style={style || __tenon_material_instance__.propMeta.style.default}>
        {text || `React: ${props.__tenon_material_instance__.propMeta.text.default}`}
      </span>
    </>
  ) as ReturnType<FC<TextProps<React.CSSProperties>>>;
}

// packages/tenon-materials/src/components/web/Atom/Text/Text.react.tsx
import React, { FC, useEffect, useRef } from 'react';
import { TextProps } from './interface';
import { createTenonEvent, useEventMeta } from '../../..';
import { RendererHost } from '@tenon/engine';

export const TextReact: FC<TextProps<React.CSSProperties>> = (props) => {
  const {
    style,
    text,
    bridge,
    __tenon_event_meta__,
    __tenon_material_instance__,
  } = props;
  const root = useRef<HTMLSpanElement>(null);
  useEventMeta(RendererHost.React, __tenon_event_meta__, root, bridge);
  useEffect(() => {
    bridge.register(createTenonEvent("onClick"), (e) => {
      console.log(__tenon_material_instance__.name, createTenonEvent("onClick"), e);
    });
    bridge.register(createTenonEvent("onDoubleClick"), (e) => {
      console.log(
        __tenon_material_instance__.name,
        createTenonEvent("onDoubleClick"),
        e
      );
    });
  }, []);
  return (
    <>
      <span ref={root} style={style}>{text}</span>
    </>
  ) as ReturnType<FC<TextProps<React.CSSProperties>>>;
}
