// apps/tenon-editor/src/workbench/editor-view.react.tsx
import { ModelImpl, ModelHost, RendererHost } from "@tenon/engine";
import { ModelChange, ModelChangeNotification, TenonEditor } from "@/core";
import { Logger } from "@/utils/logger";
import React, { FC, useEffect, useRef, useState } from "react";
import "./style/editor-style.scss";

export const EditorViewReact: FC<{
  editor: TenonEditor;
}> = (props) => {
  const editorView = useRef<HTMLDivElement | null>(null);
  const [runtimeTree, setRuntimeTree] = useState<ModelImpl[ModelHost] | null>(
    props.editor.context.dataEngine.root
  );
  const [, setRenderTick] = useState(false);

  useEffect(() => {
    const cancel = props.editor.context.on(
      ModelChange,
      async (noti: ModelChangeNotification<ModelImpl[ModelHost]>) => {
        setRenderTick((tick) => !tick);
        if (noti.payload.id === runtimeTree?.id) {
          return;
        }
        Logger.log("ModelChange", noti.payload);
        // 根节点不可拖拽
        noti.payload.draggable = false;
        cancel();
        setRuntimeTree(noti.payload);
      }
    );
    return cancel;
  }, [runtimeTree]);
  return (
    <section className="editor-view-wrapper">
      <div id="tenon-editor" ref={editorView}>
        {
          runtimeTree && props.editor.context.rendererManager
            .getRenderer(runtimeTree.name)
            .render(RendererHost.React, runtimeTree, {
              style: {
                minHeight: '680px',
              },
            })
        }
      </div>
    </section>
  ) as ReturnType<FC<{ editor: TenonEditor }>>;
}

// packages/tenon-editor/src/workbench/editor-view.vue
<template>
  <section class="editor-view-wrapper">
    <div id="tenon-editor" ref="editorView">
      <component
        v-if="runtimeTree"
        :is="
          runtimeTree.render({
            style: {
              minHeight: '680px',
            },
          })
        "
      ></component>
    </div>
  </section>
</template>
<script setup lang="ts">
import { TenonEditor } from "@/core";
import { RuntimeComponentTree } from "@/core/model";
import { ModelChange, ModelChangeNotification } from "@/core/model/notification";
import { onMounted, Ref, ref } from "vue";

const props = defineProps<{
  editor: TenonEditor;
}>();

const editorView = ref<HTMLElement>();
const runtimeTree = ref<RuntimeComponentTree | null>(props.editor.dataEngine.runtimeRoot) as Ref<RuntimeComponentTree | null>;

props.editor.context.on(ModelChange, async (noti: ModelChangeNotification) => {
  console.log("ModelChange", noti.payload);
  runtimeTree.value = noti.payload;
  // 根节点不可拖拽
  runtimeTree.value.draggable = false;
});

onMounted(async () => {
  console.log("editorView", editorView.value);
});
</script>
<style lang="scss" scoped>
.editor-view-wrapper {
  padding: 6px;
  height: 100%;
  box-sizing: border-box;
}

#tenon-editor {
  display: inline-block;
  margin-top: 20px;
  margin-bottom: 20px;
  width: 320px;
  box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.2);
}
</style>
